apiVersion: backstage.io/v1alpha1
kind: Resource
metadata:
  name: xsn5xsi7t-go-gitops
  description: This is GitOps manifest for xsn5xsi7t-go   
  links:
    - url: https://www.redhat.com/en/solutions/trusted-software-supply-chain
      title: Trusted Secure Supply Chain 
      icon: dashboard
      type: admin-dashboard
  annotations:    
    argocd/app-selector: rhtap/gitops=xsn5xsi7t-go
    backstage.io/kubernetes-id: xsn5xsi7t-go 
    backstage.io/techdocs-ref: dir:. 
    janus-idp.io/tekton: xsn5xsi7t-go
spec:
  type: gitops
  owner: user:guest 
  lifecycle: experimental
  dependsOn:
    - component:xsn5xsi7t-go
