apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: xsn5xsi7t-go
  janus-idp.io/tekton: xsn5xsi7t-go
  backstage.io/kubernetes-id: xsn5xsi7t-go
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: xsn5xsi7t-go
resources:
  - deployment.yaml
  - route.yaml
  - service.yaml
