apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: xsn5xsi7t-go
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: xsn5xsi7t-go 
  name: xsn5xsi7t-go
spec:
  ports:
  - port: 8081 
    targetPort: 8081 
  selector:
    app.kubernetes.io/instance: xsn5xsi7t-go 
